version: 2
jobs:
  py3test:
    working_directory: ~/maml
    docker:
      - image: materialsvirtuallab/circle-ci-pmg-py3:3.7.3
    steps:
      - checkout
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            conda config --set always_yes yes --set changeps1 no
            conda info -a
            conda create -q -n test-environment python=3.7 numpy scipy matplotlib sympy pandas
            source activate test-environment
            conda update --quiet numpy scipy matplotlib sympy pandas
            pip install --quiet --ignore-installed -r requirements.txt -r requirements-ci.txt
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            source activate test-environment
            pip install --quiet -e .
            pytest --cov=maml --cov-report html:coverage_reports maml
            echo "pycodestyle checks..."
            pycodestyle maml
            echo "--- Done ---"
            # coveralls
          no_output_timeout: 3600
      - store_artifacts:
          path: coverage_reports/
          destination: tr1
workflows:
  version: 2
  build_and_test:
    jobs:
      - py3test
